name: Build TWRP for CMF1

on:
  workflow_dispatch:  # This allows manual triggering via a button

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'  # You can use zulu, temurin, or adoptopenjdk

    - name: Set Git user info
      run: |
        git config --global user.name "Null Byte"
        git config --global user.email "andrexyt@proton.me"

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          repo \
          git \
          g++-multilib \
          lib32z1-dev \
          libncurses5-dev \
          libssl-dev \
          libxml2-utils \
          bison \
          build-essential \
          squashfs-tools \
          zip \
          libncurses-dev \
          zlib1g-dev \
          gcc-multilib \
          g++-multilib \
          make \
          python3 \
          python3-pip \
          curl \
          wget \
          bc \
          jq

    - name: Set up large swap memory (8GB)
      run: |
        sudo dd if=/dev/zero of=/swapfile bs=1M count=8192
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile
        sudo swapon --show

    - name: Sync the repo
      run: |
        repo init -u https://android.googlesource.com/platform/manifest
        repo sync -j4

    - name: Set up the build environment
      run: |
        . build/envsetup.sh
        lunch Tetris-userdebug

    - name: Build TWRP
      run: |
        make recoveryimage -j4

    - name: Export the TWRP artifact
      uses: actions/upload-artifact@v3
      with:
        name: twrp-recovery
        path: out/target/
